export const PROMPTS = [
  "What's the last thing you Googled that you'd be embarrassed to show someone?",
  "What's a skill you've pretended to have but never actually learned?",
  "What's the weirdest thing you've eaten and secretly enjoyed?",
  "What's the most ridiculous purchase you've ever justified to yourself?",
  "What's a movie or show you pretend to have seen but haven't?",
  "What's the pettiest reason you've ever unfollowed someone?",
  "What's your most useless talent?",
  "What's the worst haircut you've ever had?",
  "What's the most dramatic thing you've done over something trivial?",
  "What's a lie you told as a kid that spiraled completely out of control?",
  "What's the longest you've gone without showering and why?",
  "What's the most embarrassing thing your autocorrect has sent?",
  "What's an app you have on your phone that you'd never show anyone?",
  "What's the most absurd hill you're willing to die on?",
  "What's the dumbest thing you believed as a child?",
  "What's a habit you have that you'd never admit to in public?",
  "What's the most awkward thing you've done on a first date?",
  "What's the weirdest dream you've had recently?",
  "What's a food combination you love that everyone else finds disgusting?",
  "What's the most money you've spent on something completely unnecessary?",
  "What's your most shameful guilty pleasure TV show or movie?",
  "What's the worst gift you've ever given someone?",
  "What's the most childish thing you still do?",
  "What's something you've Googled but immediately closed the tab out of shame?",
  "What's the pettiest revenge you've ever gotten on someone?",
  "What's the most embarrassing thing that's happened to you in public?",
  "What's a fictional character you've had a serious crush on?",
  "What's the most ridiculous argument you've ever had with someone?",
  "What's something you've accidentally called your teacher or boss instead of their name?",
  "What's the worst job you've ever had?",
  "What's something you're surprisingly bad at for someone your age?",
  "What's the most embarrassing thing in your search history?",
  "What's a social situation you've faked being sick to get out of?",
  "What's the last time you cried at something that wasn't sad?",
  "What's an irrational fear you have that you can't explain?",
  "What's the most passive-aggressive thing you've ever done?",
  "What's the funniest misunderstanding you've ever been part of?",
  "What's the most embarrassing thing you've said in your sleep?",
  "What's a phrase or word you always mispronounce?",
  "What's the worst advice you've ever given someone that they actually followed?",
  "What's something you've stolen from a hotel room or restaurant?",
  "What's the most money you've ever lost in the dumbest way possible?",
  "What's the most embarrassing thing about your childhood bedroom?",
  "What's a song you know every single word to but won't admit it?",
  "What's the most ridiculous thing you've ever Googled at 3am?",
  "What's an accent you're convinced you do well but definitely don't?",
  "What's the most unnecessary lie you've told this week?",
  "What's something you've done in a public bathroom that you're not proud of?",
  "What's the most embarrassing voicemail you've ever left?",
  "What's a hobby you told people you have but actually gave up immediately?",
  "What's the most socially unacceptable thing you do when you're alone?",
  "What's the most embarrassing photo of yourself you've never deleted?",
  "What's the weirdest compliment you've ever received?",
  "What's the most creative excuse you've ever given for being late?",
  "What's the most embarrassing thing you've been caught doing?",
  "What's a celebrity you've seen in public and completely froze up around?",
  "What's the most expensive thing you've broken and tried to hide?",
  "What's the most childish way you've ever reacted to losing a game?",
  "What's the most dramatic thing you've texted someone and then immediately regretted?",
  "What's a word you used for years before realizing you'd been saying it wrong?",
  "What's the most embarrassing thing about your dating profile?",
  "What's a childhood nickname you had that you're glad people forgot?",
  "What's the worst thing your pet has ever done in front of company?",
  "What's the most embarrassing thing your parents have posted about you online?",
  "What's the last thing you did that made you feel like a complete idiot?",
  "What's the most overconfident thing you've ever attempted?",
  "What's a compliment you've given that was clearly a backhanded one?",
  "What's the most embarrassing autocorrect fail you've sent to a boss or teacher?",
  "What's something you've Googled right after meeting someone new?",
  "What's the most ridiculous reason you've cancelled plans?",
  "What's a show or movie you've rewatched an embarrassing number of times?",
  "What's the most shameful purchase you've made at 2am?",
  "What's the most embarrassing thing you've done to impress someone?",
  "What's a secret talent you have that nobody knows about?",
  "What's the most socially awkward thing you do on a regular basis?",
  "What's the last time you laughed until something came out of your nose?",
  "What's the most pathetic excuse you've used to avoid going to the gym?",
  "What's something you've pretended not to know to avoid responsibility?",
  "What's the most embarrassing thing about your music taste?",
  "What's the weirdest thing you've ever done when you were home alone?",
  "What's a snack combination you eat that would horrify a chef?",
  "What's the most embarrassing thing you've accidentally liked on social media?",
  "What's the most dramatic exit you've made from a situation?",
  "What's a skill you've exaggerated on your resume?",
  "What's the most ridiculous thing you've convinced yourself was healthy?",
  "What's the most embarrassing thing you've done at a work event?",
  "What's a topic you know way too much about for no good reason?",
  "What's the most overly sentimental thing you've held onto?",
  "What's the most embarrassing thing you've ever sleep-texted?",
  "What's a game you take way too seriously?",
  "What's the most ridiculous superstition you actually believe in?",
  "What's the most embarrassing thing about your internet history from 10 years ago?",
  "What's a trend you secretly participated in that you now deny?",
  "What's the most passive-aggressive meal you've ever prepared for someone?",
  "What's the most embarrassing reason you've called in sick to work?",
  "What's something you did as a teenager that still makes you cringe?",
  "What's the most expensive thing you've bought on impulse and never used?",
  "What's a phrase your parents used that you swore you'd never say and now say constantly?",
];

export function getRandomPrompt(): string {
  return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
}
